version: "3"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: techtalks/api-generierung-server
    container_name: src-solution-server
    restart: always
    tty: true
    volumes:
      - ./server/.m2:/root/.m2
    ports:
      - 8001:8080
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: techtalks/api-generierung-client
    container_name: src-solution
    restart: always
    tty: true
    volumes:
      - ./client:/var/www/html
      - /var/www/html/vendor/
    ports:
      - 8000:80
    depends_on:
      - server
