version: "3"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: techtalks/api-generierung-server
    container_name: src-solution-server
    ports:
      - 8001:8080
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: techtalks/api-generierung-client
    container_name: src-solution
    volumes:
      - ./client:/var/www/html
      - /var/www/html/vendor/
    ports:
      - 8000:80
    depends_on:
      - server
